version: '3.8'

services:
  # Backend Node.js
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pharmacy-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=pharmacy_db
      - DB_USER=postgres
      - DB_PASSWORD=pharmacy_password
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - pharmacy-network

  # Frontend React
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pharmacy-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - pharmacy-network

  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: pharmacy-postgres
    environment:
      POSTGRES_DB: pharmacy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pharmacy_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    restart: unless-stopped
    networks:
      - pharmacy-network

  # Adminer para administração do banco (opcional)
  adminer:
    image: adminer:latest
    container_name: pharmacy-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - pharmacy-network

volumes:
  postgres_data:
    driver: local

networks:
  pharmacy-network:
    driver: bridge